#!/usr/bin/env bash

set -euo pipefail

ESCAPE_CHAR="$(printf "\034")"

sanitize_variables() {
    local txt="$(cat)"
    txt=$(echo "$txt" | python3 ./scripts/trans.py )

    echo "$txt"
}

format_markdown() {
    grep -E '^[-`]' \
        | sed -E 's/:$//' \
        | sed 's/^\-/#/' \
        | sed -E 's/^`(.*)` *$/\1\'$'\n/g' \
        | sanitize_variables
}

tags_from_filename() {
    sed -E 's|[^t]*tldr/pages/||' \
        | sed 's/\.md//' \
        | tr '/' ' ' \
        | awk '{ for (i=NF; i>1; i--) printf("%s ",$i); print $1; }' \
        | sed 's/ /, /g'
}

comments_from_filename() {
    echo "; This has been extracted from"
    printf "; "
    sed -E 's|[^t]*tldr|https://github.com/tldr-pages/tldr/blob/master|'
}

format_markdown_file() {
    local -r filename="$1"
    echo "$filename" | comments_from_filename
    echo
    printf "%s" "% "
    echo "$filename" | tags_from_filename
    echo
    cat "$filename" | format_markdown
}

find_markdowns() {
    find './tldr/pages' -iname '*.md'
}

output_filename() {
    sed "s|^./tldr/|./|" \
        | sed 's/\.md/.cheat/' 
}

export_markdown() {
    local -r filename="$1"
    local -r out="$(echo "$filename" | output_filename)"
    mkdir -p "$(dirname "$out")" 2>/dev/null || true
    format_markdown_file "$filename" > "$out"
}

rm -rf "./pages"

for f in $(find_markdowns); do
    printf "Exporting $f: "
    export_markdown "$f" && echo "success" || echo "failed"
done

# format_markdown_file "./tldr/pages/common/gh-completion.md"
# format_markdown_file "./tldr/pages/common/2to3.md"
# format_markdown_file "./tldr/pages/common/apm.md"
